apiVersion: apps/v1
kind: Deployment
metadata:
  name: empresa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empresa
  template:
    metadata:
      labels:
        app: empresa
    spec:
      containers:
        - name: empresa-container
          image: keyssong/empresa:latest
          imagePullPolicy: Always           # ðŸ”¹ Sempre buscar a versÃ£o mais recente
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret